apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-demo-server
spec:
  selector:
    matchLabels:
      app: react-demo-server
  template:
    metadata:
      labels:
        app: react-demo-server
    spec:
      containers:
      - name: server
        image: walk1ng/react-demo-server:v1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1Gi
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        env:
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            value: a123456
          - name: MYSQL_DB
            value: itcast
          - name: MYSQL_SVC
            value: react-demo-db:3306