apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-root-pass
spec:
  encryptedData:
    password: AgCC94T4syL1Z1kvTFegg0NGbxjvzS5oRAEbUOTjiu5c0n178bSs5u79hIRh/J3PlDmi5XYTlswLcqx2D7nlqw8Y2DslcFZsHRVXFvf3nQ0QUub9cVmGc0FhgaU+XR096PPaeOaMm4iQHMRiGM4xlFNLtDLJZ8HcbR8BHTzJ3TqPb3pr01XnH/QTFrB0jGuh8Y3IFQgHm6u8H0rRPa+hi4Lvi/RxnzI9i41/MNZF8C0jnsFfZuZ0KXSJ1NUm5XjjAOK1e3J2p6x/etE3HHm0p27FZC7c0uaV6y+u0ctIHNkCavjIjNrz/SvD1qd/EPKO56foXeczCoo3O+ozAlVz5hu62WqpZDIcie3Kv4fv+myp7R4sI0pIlwueewDkw2EHMDPUFzknWYfEvQsrtcL8U1y4wFPiUO8eRKqLvxhrE+6ITDNCt0khm6voRwPWkPoRNUzohWMsOUMDFM/hK8xFKzU4qrpJvhtn3LflgqlqFn4t/rGeRSHXUZL0TRtStGqzRi0Xa6rli+UQ/GHITj1fEqIWq3IxrticBP7W7grvC9oFoBI4pOk+qTL6nZxCbp1BX+jOxMKsb+IiH2E+WXcprn2AQEha3I92OfMaY2uE3Ls8SV4vLySLDMoGrzStXw8yPvcfZP8r/yIv4Q+mIwcMor0zV5JhIC8N0TfTSiWchmSKL5fCfk9JDDfHBLYo5ATFVFwCRvVHkvO4
    username: AgCXGL6W2Uc9tuFIuvdBX5PEDyW6h0ouuX6K0MCT1wlO9xHVqJ6hqzFbnxCA79KFinA8ZAFJLt8ik1eVCenfKE8jrrv+MCWB2Eu3Fk/lxkwujLROMIvzk19R1Lei4KXaEjMFeqfH5xMYcQF1QJrLLM3fGzWmTloJlnXQUoEK5TbyISjUpyMUR+mLX8X3ncZflexAxEO7SuDi6mTmksHPH5g3YXFI652Kf7oaBcEE3Dcbk5fh2nteU+vcZHg9HNSr2ALruICwWkd50x6/88FeI1E9zAytjjNcaEZ9tIZoLtzwG71HOONeAZsjhr2XBav+5MeCjzPM+4Pr41isQCvlKLUmZcAvLy8tbNBjEbA3C7itVgmthvRyeKCjREPwQnRtTQ9TQyC5XvJo8D6++FM92T6KPcg7JWj4RJCVLidN7FDZ9lLL+rbRAadPgNQ1wrFUcMn4+DlfmZXQhbMn8WXgFaJjBj85KHTxrqTuOAtMM6LXQV0h6Xq37saGsBN6Y3c1pV64/53SrmAlB5tDmShxVljKJzuHjalPyItfN3TXSw5z8VHBhFPjLFGD85vo682Ms0lXxIHd2tnu8hUP3gww8AqaAuN8lluQTq/PQPwZSSqAmQHdaqSsDrsxA/LZe85wGeQblzi/yxFiN3rK1cxcwZzNVRzum2JtwFFSKGjFjMssRGBQOYXLQjwq2LfGX1u1WCN+iQWy
  template:
    metadata:
      creationTimestamp: null
      name: mysql-root-pass
    type: Opaque

