apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- mysql.yaml
images:
- name: walk1ng/react-demo-server
  newTag: 8198e2794bf4627b0bf48140bb81bb8dfd906438
