apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-server-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-ns-reader
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-ns-reader-binding
subjects:
- kind: ServiceAccount
  name: app-server-sa
roleRef:
  kind: Role
  name: pod-ns-reader
  apiGroup: rbac.authorization.k8s.io

